[project]
name = "marklogic"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "clip",
    "faiss-cpu>=1.12.0",
    "flask>=3.1.2",
    "ftfy>=6.3.1",
    "numpy>=2.3.4",
    "pillow>=12.0.0",
    "psycopg2-binary>=2.9.11",
    "pymupdf>=1.26.5",
    "regex>=2025.11.3",
    "sentence-transformers>=5.1.2",
    "torch>=2.9.0",
    "tqdm>=4.67.1",
]

[tool.uv.sources]
clip = { git = "https://github.com/openai/CLIP.git" }
